### PR TITLE
JS SDK Fixes

### PR DESCRIPTION
**Pull request by akshaygarg86**
Three changes:

1. Readme update
2. Allow for multiple responses in the device discovery scenario
3. Subscribe to relevant dab messages only

### CODE REVIEW

**Comment by GaganBhat** [comment]
@akshaygarg86 I think changing all routes in order to support discovery is not preferred. It doesn't make sense from implementer perspective to return an array [] for every response when the spec dictates an object.

Each process() function has the perspective of only 1 single device only, we can't ask implementers to return an array of discovery responses for many devices, it don't logically follow. At the implementation level they only keep track of 1 active device.

We can solve this by having MQTT handlers at a per-device-operation level rather than at a bridge level.

For example, currently the proposed design is such that:
```
single dab/discovery handler <-->  [] return array of discovery responses from single process()
```

Instead it could be:

```
dab/discovery handler for deviceID X <--> discovery response
dab/discovery handler for deviceID Y <--> discovery response
dab/discovery handler for deviceID Z <--> discovery response
...
```

I can help tackle this problem with a refactor to the structure that I am currently working on.

**Comment by akshaygarg86** [comment]
> @akshaygarg86 I think changing all routes in order to support discovery is not preferred. It doesn't make sense from implementer perspective to return an array [] for every response when the spec dictates an object.
> 
> Each process() function has the perspective of only 1 single device only, we can't ask implementers to return an array of discovery responses for many devices, it don't logically follow. At the implementation level they only keep track of 1 active device.
> 
> We can solve this by having MQTT handlers at a per-device-operation level rather than at a bridge level.
> 
> For example, currently the proposed design is such that:
> 
> ```
> single dab/discovery handler <-->  [] return array of discovery responses from single process()
> ```
> 
> Instead it could be:
> 
> ```
> dab/discovery handler for deviceID X <--> discovery response
> dab/discovery handler for deviceID Y <--> discovery response
> dab/discovery handler for deviceID Z <--> discovery response
> ...
> ```
> 
> I can help tackle this problem with a refactor to the structure that I am currently working on.

Agreed with the high level thinking. But I see a few issues here:

1. Purpose of discovery action is to independently identify a list of DAB capable device-ids (of a specific type) in the setup. This maybe done to say confirm the device-id list that the test infra has. But if we want to leverage the discovery handler on a per device-id basis (added to the bridge by user client) then its not truly serving its purpose since we are just limiting discovery to the device list that user client already knows i.e. its becoming more of a health check rather than a true discovery.

2. We are not passing deviceId in the process calls so currently each of it seems like a generic operation decoupled from a specific device. This can be addressed though by simply passing the deviceId to the process call.

Maybe we dont have to return arrays from the individual process routines except for discovery. And then we can just do a type check at the bridge.js/index.js level to see if an array or a single object was returned?

**Comment by GaganBhat** [comment]
> We are not passing deviceId in the process calls so currently each of it seems like a generic operation decoupled from a specific device. 

This is a good call-out that I think we need to fix. The goal is that partners who implement this bridge don't need worry about managing multiple devices during runtime and instead focus simply on the input / output per operation per device. My assumption was that the IP address for the device was saved in the execution context, but I see this is not the case since everything is static.

I really do think that the inheritance model with DAB 1.0 solves all of these problems and much more. This just double-confirms it.

But for now:

> Maybe we dont have to return arrays from the individual process routines except for discovery. And then we can just do a type check at the bridge.js/index.js level to see if an array or a single object was returned?

Agreed, I think this is best approach instead of making every process() an array return.

**Comment by akshaygarg86** [comment]
Sounds good. Let me edit my PR in that case. Meanwhile please see if other changes look ok.

**Comment by GaganBhat** [comment]
The other changes regarding README updates and subscription of only relevant device specific DAB messages LGTM 👍

**Pull request closed without merging**
